server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    # url: jdbc:mysql://13.124.253.115:3306/security?serverTimezone=Asia/Seoul
    url: jdbc:mysql://13.124.253.115:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cos
    password: cos1234

#  Mustache ?? ?? ?(?? ??)
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
